version: 0.0
os: linux
files:
    - source: ./
      destination: /home/ec2-user/open_fmri
hooks:
  ApplicationStop: 
    - location: scripts/stop_container.sh 
      timeout: 60 
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
      runas: ec2-user
