version: 0.1
os: linux
files:
    - source: ./
      destination: /home/ec2-user/open_fmri
permissions:
    - object: /home/ec2-user/open_fmri
      pattern: "*"
      owner: ec2-user
      group: ec2-user
      mode: 644
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 60
      runas: ec2-user
