postgres:
    image: postgres:9.4
    volumes:
        - /data/test/postgres:/var/lib/postgresql/data
    env_file: .env
    expose:
        - "5432"
uwsgi:
    build: .
    restart: always
    user: open_fmri
    volumes:
        - .:/app 
        - /var/www/static
    links:
        - postgres
    env_file: .env
    command: /app/uwsgi.sh

#For development well have the nginx.conf and uwsgi params as volumes for easy
#testing. In development we might remove these volumes and uncomment the add 
#file lines in the nginx dockerfile to make a more portable image.
nginx:
    image: nginx:latest
    volumes_from:
        - uwsgi
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
    links:
        - uwsgi
    ports:
        - "0.0.0.0:80:80"


