postgres_data:
    image: busybox
    volumes:
        - /var/lib/postgres
    command: /bin/sh

postgres:
    image: postgres:9.4
    volumes_from:
        - postgres_data
    env_file: .env
    expose:
        - "5432"

uwsgi:
    build: .
    restart: always
    volumes:
        - .:/app 
        - /var/www/static
    links:
        - postgres
    env_file: .env
    command: /app/uwsgi.sh
    expose:
        - "4000"
    working_dir: /app

nginx:
    image: nginx:latest
    volumes_from:
        - uwsgi
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
        - .ssl/nginx.crt:/etc/nginx/nginx.crt:ro
        - .ssl/nginx.key:/etc/nginx/nginx.key:ro
        #- .ssl/dhparam.pem:/etc/nginx/dhparam.pem:ro
        #- ./.htpasswd:/etc/nginx/.passwd:ro
    links:
        - uwsgi
    ports:
        - "0.0.0.0:80:80"
        - "0.0.0.0:443:443"

redis:
    restart: always
    image: redis

worker:
    build: .
    command: celery worker -A open_fmri.celery -Q default -n default@%h --loglevel=debug
    env_file: .env
    volumes:
        - .:/app
    volumes_from:
        - uwsgi
    links:
        - redis
    working_dir: /app


opensmtpd:
    build: ./opensmtpd/
    volumes:
        - ./opensmtpd/smtpd.conf:/etc/smtpd.conf
        - ./opensmtpd/forward:/etc/.forward
        - ./opensmtpd/credentials:/etc/.credentials
    ports:
        - "0.0.0.0:25:25"
