postgres_data:
    image: busybox
    volumes:
        - /var/lib/postgres
    command: /bin/sh

postgres:
    image: postgres:9.4
    volumes_from:
        - postgres_data
    env_file: .env
    expose:
        - "5432"
uwsgi:
    build: .
    restart: always
    volumes:
        - .:/app 
        - /var/www/static
    links:
        - postgres
    env_file: .env
    command: /app/uwsgi.sh
    expose:
        - "4000"
    working_dir: /app

#For development well have the nginx.conf and uwsgi params as volumes for easy
#testing. In development we might remove these volumes and uncomment the add 
#file lines in the nginx dockerfile to make a more portable image.
nginx:
    image: nginx:latest
    volumes_from:
        - uwsgi
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
        - ./nginx.crt:/etc/nginx/nginx.crt:ro
        - ./nginx.key:/etc/nginx/nginx.key:ro
        - ./.htpasswd:/etc/nginx/.passwd:ro
    links:
        - uwsgi
    ports:
        - "0.0.0.0:80:80"
        - "0.0.0.0:443:443"
